name: rl-sandbox
version: 0.1.0.0

ghc-options: -Wall

default-extensions:
  - BangPatterns
  - LambdaCase
  - OverloadedStrings
  - ViewPatterns

dependencies:
  - base
  - mwc-random
  - primitive
  - statistics
  - vector
  - unordered-containers

library:
  source-dirs: src

tests:
  doctest:
    main: DocTest.hs
    source-dirs: test
    dependencies:
      - rl-sandbox
      - doctest

  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - rl-sandbox
      - hspec

benchmarks:
  convergence:
    source-dirs: benchmark/convergence
    main: Main.hs
    dependencies:
      - Chart
      - Chart-diagrams
      - blaze-html
      - blaze-markup
      - rl-sandbox

